### ISSUE TITLE
Distribution proposal: support reverse-lookup from a manifest to its referrers (such as an index)

### ISSUE THREAD

**Issue by avtakkar** [notaryproject/nv2#13]
With regards to the manifest referrer metadata store discussed in https://github.com/notaryproject/nv2/pull/14, two options come to mind for implementing the reverse lookup:

1. Let each manifest have a reverse lookup to all indexes that reference it. Retrieving referrer metadata for a particular manifest would mean first retrieving the indexes, and then following their references to the config objects to get the requested metadata references.

2. Let each manifest have a reverse lookup to all config objects referenced by indexes that reference the manifest. This approach short circuits the indexes from the reverse lookup, providing direct access to the referrer metadata.

**Comment by SteveLasker** [comment]
Closing as this is being tracked through the proposed [reference type working group](https://github.com/opencontainers/tob/issues/96), with the current design tracked through [oci.artifact.manifest PR #29](https://github.com/opencontainers/artifacts/pull/29)
