### ISSUE TITLE
Support for GPG?

### ISSUE THREAD

**Issue by jdolitsky** [notaryproject/nv2#21]
Noticed that the prototype uses x509 certs.

What are the reasons (if any) that GPG is insufficient/unsupported?

**Comment by SteveLasker** [comment]
@shizhMSFT, can you remind us of where we landed on supporting gpg? We initially removed it as we felt it invalidated the secure x509 cert flows. But, I thought you brought it back. Can you elaborate?

**Comment by dlorenc** [comment]
I would be opposed to directly supporting or encouraging the use of GPG going forward.

**Comment by jdolitsky** [comment]
@dlorenc - interesting read, thanks for sharing
