### ISSUE TITLE
update `docker nv2 push` to use reference

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/nv2#46]
The current nv2 client uses `link`, instead of `reference`. 
To clean up loose ends:
  `docker push $IMAGE`
The output should change from:
  The push refers to repository [registry.wabbit-networks.io/net-monitor]
  8ea3b23f387b: Preparing
  8ea3b23f387b: Pushed
  v1: digest: sha256:31c6d76b9a0af8d2c0a7fc16b43b7d8d9b324aa5ac3ef8c84dc48ab5ba5c0f49 size: 527
  Pushing signature
  signature: digest: sha256:dfad94dbda48a0a221a6196ee802b628d84a1551fecac6e94af306aff2f7b07d size: 2534
  **link**: digest: sha256:8eb7394c8f287ebd0e84a4659f37a2688c6e07e39906933ccb83d9011fb29034 size: 470
to
  The push refers to repository [registry.wabbit-networks.io/net-monitor]
  8ea3b23f387b: Preparing
  8ea3b23f387b: Pushed
  v1: digest: sha256:31c6d76b9a0af8d2c0a7fc16b43b7d8d9b324aa5ac3ef8c84dc48ab5ba5c0f49 size: 527
  Pushing signature
  signature: digest: sha256:dfad94dbda48a0a221a6196ee802b628d84a1551fecac6e94af306aff2f7b07d size: 2534
  **reference**: digest: sha256:8eb7394c8f287ebd0e84a4659f37a2688c6e07e39906933ccb83d9011fb29034 size: 470

**Comment by SteveLasker** [comment]
Assinging to @shizhMSFT

**Comment by shizhMSFT** [comment]
This issue is covered by #47.
